### ISSUE TITLE
module does not exist

### ISSUE THREAD

**Issue by Worldofmatthew** [cshoredaniel/new-oldnew-mashup#68]
Hello,

I attempted to install this theme by the instructions provided but I get this error when I try to run the site. 

Error: module "github.com/cshoredaniel/krisk-Fuse" not found; either add it as a Hugo Module or store it in "c:\\worldofmatthew.com\\themes".: module does not exist

Any help would be most welcome.

Thank You for reading.

**Comment by cshoredaniel** [comment]
Hi!

I've just tested this on Windows with Hugo 0.60.0 and noticed two deficiencies in the documentation.
The first is the the theme directory **must** be named ``new-oldnew-mashup`` (so in your case, ``C:\worldofmatthew.com\themes\new-oldnew-mashup").
The other is thing I noticed is that if deploying the theme from an archive (ZIP or tar.gz), and try to just copy the ``config.toml`` from ``exampleSite`` in the theme, the build will fail complaining about not being a git repo.  The fix for that is to make sure you do **not** have ``enableGitInfo = true`` in your ``config.toml``.
With those adjustments the site ought to build.

I hope you closed the issue because you got it working, but I wanted to add docs for others who might find the issue, and in case you are still willing to try if you had given up.

Thanks for reporting!
